// Mocks generated by Mockito 5.0.16 from annotations
// in space_pictures/test/application/photo_list/photo_list_bloc_test.dart.
// Do not manually edit this file.

import 'dart:async' as _i3;

import 'package:mockito/mockito.dart' as _i1;
import 'package:space_pictures/domain/photo_list/photo_element.dart' as _i4;
import 'package:space_pictures/infrastructure/photo_list/photo_list_service.dart'
    as _i2;

// ignore_for_file: avoid_redundant_argument_values
// ignore_for_file: avoid_setters_without_getters
// ignore_for_file: comment_references
// ignore_for_file: implementation_imports
// ignore_for_file: invalid_use_of_visible_for_testing_member
// ignore_for_file: prefer_const_constructors
// ignore_for_file: unnecessary_parenthesis
// ignore_for_file: camel_case_types

/// A class which mocks [PhotoListService].
///
/// See the documentation for Mockito's code generation for more information.
class MockPhotoListService extends _i1.Mock implements _i2.PhotoListService {
  MockPhotoListService() {
    _i1.throwOnMissingStub(this);
  }

  @override
  _i3.Future<List<_i4.PhotoElement>> getAllPhoto() =>
      (super.noSuchMethod(Invocation.method(#getAllPhoto, []),
              returnValue:
                  Future<List<_i4.PhotoElement>>.value(<_i4.PhotoElement>[]))
          as _i3.Future<List<_i4.PhotoElement>>);
  @override
  _i3.Future<List<_i4.PhotoElement>> getAllPhotoLocal() =>
      (super.noSuchMethod(Invocation.method(#getAllPhotoLocal, []),
              returnValue:
                  Future<List<_i4.PhotoElement>>.value(<_i4.PhotoElement>[]))
          as _i3.Future<List<_i4.PhotoElement>>);
  @override
  dynamic savePhotoLocal(_i4.PhotoElement? photoElement) =>
      super.noSuchMethod(Invocation.method(#savePhotoLocal, [photoElement]));
  @override
  String toString() => super.toString();
}
