// Mocks generated by Mockito 5.0.16 from annotations
// in space_pictures/test/infrastructure/photo_list/photo_list_service_test.dart.
// Do not manually edit this file.

import 'dart:async' as _i3;

import 'package:mockito/mockito.dart' as _i1;
import 'package:space_pictures/domain/photo_list/photo_element.dart' as _i4;
import 'package:space_pictures/infrastructure/database_and_api/photo_element_dto.dart'
    as _i5;
import 'package:space_pictures/infrastructure/photo_list/photo_list_repository.dart'
    as _i2;

// ignore_for_file: avoid_redundant_argument_values
// ignore_for_file: avoid_setters_without_getters
// ignore_for_file: comment_references
// ignore_for_file: implementation_imports
// ignore_for_file: invalid_use_of_visible_for_testing_member
// ignore_for_file: prefer_const_constructors
// ignore_for_file: unnecessary_parenthesis
// ignore_for_file: camel_case_types

/// A class which mocks [PhotoListRepository].
///
/// See the documentation for Mockito's code generation for more information.
class MockPhotoListRepository extends _i1.Mock
    implements _i2.PhotoListRepository {
  MockPhotoListRepository() {
    _i1.throwOnMissingStub(this);
  }

  @override
  _i3.Future<List<_i4.PhotoElement>> getAllPhotoList() =>
      (super.noSuchMethod(Invocation.method(#getAllPhotoList, []),
              returnValue:
                  Future<List<_i4.PhotoElement>>.value(<_i4.PhotoElement>[]))
          as _i3.Future<List<_i4.PhotoElement>>);
  @override
  _i3.Future<List<_i4.PhotoElement>> getAllPhotoLocalList() =>
      (super.noSuchMethod(Invocation.method(#getAllPhotoLocalList, []),
              returnValue:
                  Future<List<_i4.PhotoElement>>.value(<_i4.PhotoElement>[]))
          as _i3.Future<List<_i4.PhotoElement>>);
  @override
  dynamic savePhotoLocal(_i5.PhotoElementDTO? photoElementDTO) =>
      super.noSuchMethod(Invocation.method(#savePhotoLocal, [photoElementDTO]));
  @override
  String toString() => super.toString();
}
